[project]
name = "langgraph-templete"
version = "1.1.1"
description = "A template for langgraph projects"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-google-genai>=4.0.0",
    "langgraph>=1.0.4",
]
